// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using OnlineCourse.Entity;
using System;

namespace OnlineCourse.Entity.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20171231185433_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("OnlineCourse.Entity.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte?>("AccessLevel");

                    b.Property<string>("ActivationCode")
                        .HasMaxLength(20);

                    b.Property<string>("Addrress")
                        .HasMaxLength(200);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .HasMaxLength(400);

                    b.Property<string>("Email")
                        .HasMaxLength(100);

                    b.Property<DateTime?>("ExpireDate")
                        .HasColumnType("datetime");

                    b.Property<string>("FullName")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime");

                    b.Property<string>("LastLoginIp")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("LastRequestActivationCode")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("LastResetPasswordDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("LastVisitedNewsId");

                    b.Property<int?>("LoginAttemptFailure");

                    b.Property<string>("Mobile")
                        .HasMaxLength(50);

                    b.Property<string>("MobileCreditAlarm")
                        .HasMaxLength(100);

                    b.Property<string>("Password")
                        .HasMaxLength(200);

                    b.Property<string>("Phone")
                        .HasMaxLength(50);

                    b.Property<string>("Position")
                        .HasMaxLength(30);

                    b.Property<int?>("RegisterAttemptFailure");

                    b.Property<DateTime?>("RegisterDate")
                        .HasColumnType("datetime");

                    b.Property<string>("SecuritySpan");

                    b.Property<byte?>("State");

                    b.Property<string>("UserName")
                        .HasMaxLength(100);

                    b.Property<byte?>("ValidEmail");

                    b.Property<byte?>("ValidMobile");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
